FROM rocker/tidyverse:devel
ENV TZ=Australia/Sydney
RUN date

# System dependencies (apt-get since r-base is debian based)
RUN apt-get update
RUN apt-get install -y libcurl4-gnutls-dev curl # curl files
RUN apt-get install -y docker.io # docker interface
RUN apt-get install -y gnupg2 # required to install odbc

# Move pak.lock to the container
COPY . /app/
WORKDIR /app

# tex packages are installed in /root/bin so we have to make sure those
# packages accessible by adding that directory to the PATH variable.
ENV PATH="${PATH}:/root/bin"

RUN R -e 'install.packages("pak")'

RUN R -e 'getwd(); dir()'

# Remove dev package from pak.lock
RUN R -e 'pak::pak("jsonlite"); d <- jsonlite::read_json("pak.lock"); d$packages <- Filter(\(x) x$package != "SCDB", d$packages); print(unlist(Map(\(x) x$package, d$packages))); jsonlite::write_json(d, "pak.lock", auto_unbox = TRUE)'

# Install package dependencies
RUN R -e 'pkgs <- jsonlite::fromJSON("pak.lock")$packages; pak::pak(paste0(pkgs$package, "@" ,pkgs$version))'

# Install workflow dependencies
RUN R -e 'pak::pak(c("jsonlite", "rcmdcheck", "devtools", "lintr", "covr", "roxygen2", "pkgdown", "rmarkdown", "styler"))'

# Install the dev package
RUN R -e 'devtools::install()'
