# dbplyr needs additional implementation for Oracle to work.

# The ANALYZE TABLE command generated by dplyr does not work for Oracle, so we manually implement.
#' @exportS3Method dbplyr::sql_table_analyze
#' @noRd
sql_table_analyze.JDBCConnection <- function(con, table, ...) {
  dbplyr::build_sql(
    "ANALYZE TABLE ",
    dbplyr::as.sql(id(table, conn = con), con = con),
    " COMPUTE STATISTICS",
    con = con
  )
}

#' @importFrom DBI dbGetRowsAffected
NULL

#' @importFrom rJava .jcall
#' @exportMethod dbGetRowsAffected
#' @noRd
setMethod("dbGetRowsAffected", "JDBCResult", function(res, ...) {
  if (!is.null(res@stat)) {
    tryCatch({
      cnt <- rJava::.jcall(res@stat, "I", "getUpdateCount")
      return(if (cnt < 0) 0L else as.integer(cnt))
    }, error = function(e) {
      return(NA_integer_)
    })
  }
  return(NA_integer_)
})


#' @importFrom DBI dbQuoteIdentifier
NULL


#' Quote identifiers for Oracle
#'
#' @name dbQuoteIdentifier
#' @param conn A JDBCConnection
#' @param x Identifiers to quote
#' @param ... Additional arguments (ignored)
#' @return SQL object with quoted identifiers
#' @importClassesFrom RJDBC JDBCConnection
#' @exportMethod dbQuoteIdentifier
#' @noRd
setMethod("dbQuoteIdentifier", signature("JDBCConnection", "character"),
  function(conn, x, ...) {
    x <- enc2utf8(x)

    reserved_words <- c("DATE", "NUMBER", "VARCHAR")

    needs_escape <- (grepl("^[a-zA-Z_]", x) & toupper(x) != x) |  tolower(x) %in% reserved_words

    x[needs_escape] <- paste0("\"", gsub("\"", "\"\"", x[needs_escape]), "\"")

    return(DBI::SQL(x, names = names(x)))
  }
)


#' @rdname dbQuoteIdentifier
#' @exportMethod dbQuoteIdentifier
#' @noRd
setMethod("dbQuoteIdentifier", signature("DBIConnection", "Id"),
  function(conn, x, ...) {

    # For `Id`, run on each non-NA element
      return(DBI::SQL(paste0(DBI::dbQuoteIdentifier(conn, purrr::discard(x@name, is.na)), collapse = ".")))
  }
)

#' @importFrom DBI dbCreateTable
NULL

#' @exportMethod dbCreateTable
#' @noRd
setMethod("dbCreateTable", signature("JDBCConnection", "Id"),
  function(conn, name, fields, ..., row.names = NULL, temporary = FALSE) {
    stopifnot(is.null(row.names))
    stopifnot(is.logical(temporary), length(temporary) == 1L)
    query <- DBI::sqlCreateTable(con = conn, table = name, fields = fields,
        row.names = row.names, temporary = temporary, ...)
    print(query)
    DBI::dbExecute(conn, query)
    invisible(TRUE)
  }
)

#' @importFrom DBI dbWriteTable
NULL

#' @importFrom odbc dbWriteTable
NULL

#' @exportMethod dbWriteTable
#' @noRd
setMethod("dbWriteTable", signature("JDBCConnection", "SQL", "data.frame"),
  function(conn, name, value, ...) {

    # Use the odbc method for JDBCConnections also
    odbc_method <- getMethod(dbWriteTable, signature(conn = "OdbcConnection", name = "SQL", value = "data.frame"))

    odbc_method@.Data(conn, name, value, ...)

  }
)